@startuml
'https://plantuml.com/sequence-diagram

class Solution44{
Loads JSONArray at and sends it
to the product Search
Function LoadProductList();
}

class ProductSearch{
allows user to search for a
product using a JSONArray
FUNCTION: JSONproductSearch()
}

Solution44--|>ProductSearch
@enduml