@startuml
'https://plantuml.com/class-diagram


class Solution45 {
(PROMTS FOR *FILENAME*)
Function: InputFileCopy()
}

class FindAndReplace {
(REPLACES STRINGS IN OUTPUT FILE)
Function: replaceWith()
Function: replaceWords()
Function: indAndReplaceWithHashmaps()
}

Solution45 --|> FindAndReplace
@enduml